namespace: nibss
name: cisco_fmc
version: 1.0.0
readme: README.md
authors:
- David Adelowo (GitHub > @amotolani)
description: Ansible Network Collection for Cisco FMC.
license:
- GPL-2.0-or-later
tags:  [fmc, cisco, networking]
repository: https://github.com/nibss-dev/ansible-collections
documentation: https://github.com/nibss-dev/ansible-collections/tree/master/docs
issues: https://github.com/nibss-dev/ansible-collections/issues
