namespace: amotolani
name: cisco_fmc
version: 1.1.5
readme: README.md
authors:
- David Adelowo (GitHub > @amotolani)
description: Ansible Network Collection for Cisco FMC.
license:
- GPL-2.0-or-later
tags:  [fmc, cisco, networking]
repository: https://github.com/amotolani/fmc_collections
documentation: https://github.com/amotolani/fmc_collections/tree/master/amotolani/cisco_fmc/docs
issues: https://github.com/amotolani/fmc_collections/issues
build_ignore:
  - changelogs
