namespace: amotolani
name: cisco_fmc
version: 1.0.8
readme: README.md
authors:
- David Adelowo (GitHub > @amotolani)
description: Ansible Network Collection for Cisco FMC.
license:
- GPL-2.0-or-later
tags:  [fmc, cisco, networking]
repository: https://github.com/nibss-dev/fmc_collections
documentation: https://github.com/nibss-dev/fmc_collections/tree/master/docs
issues: https://github.com/nibss-dev/fmc_collections/issues
build_ignore:
  - changelogs